### ISSUE TITLE
pymodbus scripts not working

### ISSUE THREAD

**Issue by jimlynnjulian** [kasbert/epsolar-tracer#63]
NOTE: I found that the highest version of pymodbus that would install is 2.5.0 in Buster, kernel: 5.10.103-v7l+, RPi 4.
I had problems with Bookworm, so I decided to inistall period software for the greatest compatibility.
A lightning strike damaged my solar power station and I'm rebuilding the software environment. The system ran several years without much of a problem, on a RPi 3b+. However, in all that time, I don't think I ever ran the scripts in question, so I don't know for sure if this an update problem or whether the scripts would never have ran in my systrem configuration..
The two scripts ane not neccessary in my system, so this is not an urgent or even critical issue. Thanks for the software.

Installed latest version your software.

Running.

Tried the 'info.py' and 'readall.py' scripts in python2 and 3:

`pi@raspberrypi:/var/www/html/epsolar $ python info.py
Traceback (most recent call last):
  File "info.py", line 3, in <module>
    from pyepsolartracer.client import EPsolarTracerClient
  File "/var/www/html/epsolar/pyepsolartracer/client.py", line 4, in <module>
    from pymodbus.client import ModbusSerialClient as ModbusClient
ImportError: cannot import name ModbusSerialClient

pi@raspberrypi:/var/www/html/epsolar $ python3 info.py
Traceback (most recent call last):
  File "info.py", line 3, in <module>
    from pyepsolartracer.client import EPsolarTracerClient
  File "/var/www/html/epsolar/pyepsolartracer/client.py", line 4, in <module>
    from pymodbus.client import ModbusSerialClient as ModbusClient
ImportError: cannot import name 'ModbusSerialClient' from 'pymodbus.client' (/home/pi/.local/lib/python3.7/site-packages/pymodbus/client/__init__.py)
`

**Comment by jimlynnjulian** [comment]
minimalmodbus is not loadable.
pi@raspberrypi:/var/www/html/epsolar $ python info.py
Traceback (most recent call last):
  File "info.py", line 3, in <module>
    from pyepsolartracer.client import EPsolarTracerClient
  File "/var/www/html/epsolar/pyepsolartracer/client.py", line 4, in <module>
    from pymodbus.client import ModbusSerialClient as ModbusClient
ImportError: cannot import name ModbusSerialClient

**Comment by jimlynnjulian** [comment]
Closing. This turned out to be a version issue. The opsys and package version could not be matched.
The driver works, though, just not the test scripts.; info.py, readall.py, testdata.py
